apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # deployment name
  name: mel-app
  labels:
    app: mel-app
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: mel-app
  # pod template
  template:
    metadata:
      labels:
        app: mel-app
        version: v1.0.0
    spec:
      # pod contains 1 container
      containers:
      - name: mel-app
        image: securitydemoacr.azurecr.io/nodejs-server:latest
        # container opens port 80
        ports:
        - containerPort: 80
          name: http
          protocol: TCP   
        - containerPort: 80
          name: probe               
        env:
        - name: VERSION
          value: v1.0.0
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 20
          failureThreshold: 2
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 20
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  # The unique Service instance/name
  name: node-service
spec:
  # Add external load balancer
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: mel-app